"""initial persistence schema

Revision ID: 6f0aad6e5b27
Revises: 
Create Date: 2026-08-09 20:37:38.435555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

# revision identifiers, used by Alembic.
revision: str = '6f0aad6e5b27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('totp_secret_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('lookup_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), nullable=False),
    sa.Column('record_kind', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('endpoint', sa.String(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('payload_codec', sa.String(length=32), nullable=False),
    sa.Column('plaintext_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fresh_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stale_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_usable', sa.Boolean(), nullable=False),
    sa.Column('unusable_reason', sa.String(length=256), nullable=True),
    sa.Column('encryption_scheme', sa.String(length=32), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=128), nullable=True),
    sa.Column('encryption_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fresh_until >= observed_at', name=op.f('ck_lookup_record_fresh_after_observed')),
    sa.CheckConstraint('stale_until IS NULL OR stale_until >= fresh_until', name=op.f('ck_lookup_record_stale_after_fresh')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookup_record')),
    sa.UniqueConstraint('namespace', 'cache_key', 'content_hash', 'observed_at', name=op.f('uq_lookup_record_namespace'))
    )
    op.create_index('ix_lookup_record_created_at', 'lookup_record', ['created_at'], unique=False)
    op.create_index('ix_lookup_record_key_observed', 'lookup_record', ['namespace', 'cache_key', 'observed_at'], unique=False)
    op.create_table('lookup_refresh_lease',
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'cache_key', name=op.f('pk_lookup_refresh_lease'))
    )
    op.create_index('ix_lookup_refresh_lease_until', 'lookup_refresh_lease', ['lease_until'], unique=False)
    op.create_table('public_suffix_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule', sa.String(length=253), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_suffix_rule')),
    sa.UniqueConstraint('rule', name=op.f('uq_public_suffix_rule_rule'))
    )
    op.create_table('lookup_cache_head',
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['lookup_record.id'], name=op.f('fk_lookup_cache_head_record_id_lookup_record'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('namespace', 'cache_key', name=op.f('pk_lookup_cache_head'))
    )
    op.create_table('managed_domain',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name_ascii', sa.String(length=253), nullable=False),
    sa.Column('name_unicode', sa.String(length=253), nullable=False),
    sa.Column('registrable_domain', sa.String(length=253), nullable=False),
    sa.Column('public_suffix', sa.String(length=253), nullable=False),
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.Column('registrar_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('statuses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registry_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nameservers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dnssec_enabled', sa.Boolean(), nullable=True),
    sa.Column('latest_source', sa.String(length=16), nullable=True),
    sa.Column('last_successful_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outcome', sa.String(length=32), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), nullable=False),
    sa.Column('renewal_mode', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_managed_domain_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managed_domain')),
    sa.UniqueConstraint('user_id', 'name_ascii', name=op.f('uq_managed_domain_user_id'))
    )
    op.create_index('ix_managed_domain_expires_at', 'managed_domain', ['expires_at'], unique=False)
    op.create_index('ix_managed_domain_schedule', 'managed_domain', ['monitor_enabled', 'next_check_at'], unique=False)
    op.create_table('parsed_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lookup_record_id', sa.Uuid(), nullable=False),
    sa.Column('parser_key', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_record_id'], ['lookup_record.id'], name=op.f('fk_parsed_snapshot_lookup_record_id_lookup_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parsed_snapshot')),
    sa.UniqueConstraint('lookup_record_id', 'parser_key', 'parser_version', 'schema_version', name=op.f('uq_parsed_snapshot_lookup_record_id'))
    )
    op.create_table('security_audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_security_audit_event_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_audit_event'))
    )
    op.create_table('domain_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('managed_domain_id', sa.Uuid(), nullable=False),
    sa.Column('lookup_record_id', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=2048), nullable=True),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('parser_key', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_record_id'], ['lookup_record.id'], name=op.f('fk_domain_check_lookup_record_id_lookup_record'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['managed_domain_id'], ['managed_domain.id'], name=op.f('fk_domain_check_managed_domain_id_managed_domain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_check'))
    )
    op.create_index('ix_domain_check_domain_checked', 'domain_check', ['managed_domain_id', 'checked_at'], unique=False)
    op.create_index('ix_domain_check_outcome_checked', 'domain_check', ['outcome', 'checked_at'], unique=False)
    op.create_table('notification_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('managed_domain_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('channel_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['managed_domain_id'], ['managed_domain.id'], name=op.f('fk_notification_rule_managed_domain_id_managed_domain'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_rule_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rule'))
    )
    op.create_table('notification_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_rule_id', sa.Uuid(), nullable=False),
    sa.Column('managed_domain_id', sa.Uuid(), nullable=False),
    sa.Column('domain_check_id', sa.Uuid(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_check_id'], ['domain_check.id'], name=op.f('fk_notification_outbox_domain_check_id_domain_check'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['managed_domain_id'], ['managed_domain.id'], name=op.f('fk_notification_outbox_managed_domain_id_managed_domain'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_rule_id'], ['notification_rule.id'], name=op.f('fk_notification_outbox_notification_rule_id_notification_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox')),
    sa.UniqueConstraint('deduplication_key', name=op.f('uq_notification_outbox_deduplication_key'))
    )
    op.create_index('ix_notification_outbox_status_available', 'notification_outbox', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_outbox_status_available', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_table('notification_rule')
    op.drop_index('ix_domain_check_outcome_checked', table_name='domain_check')
    op.drop_index('ix_domain_check_domain_checked', table_name='domain_check')
    op.drop_table('domain_check')
    op.drop_table('security_audit_event')
    op.drop_table('parsed_snapshot')
    op.drop_index('ix_managed_domain_schedule', table_name='managed_domain')
    op.drop_index('ix_managed_domain_expires_at', table_name='managed_domain')
    op.drop_table('managed_domain')
    op.drop_table('lookup_cache_head')
    op.drop_table('public_suffix_rule')
    op.drop_index('ix_lookup_refresh_lease_until', table_name='lookup_refresh_lease')
    op.drop_table('lookup_refresh_lease')
    op.drop_index('ix_lookup_record_key_observed', table_name='lookup_record')
    op.drop_index('ix_lookup_record_created_at', table_name='lookup_record')
    op.drop_table('lookup_record')
    op.drop_table('app_user')
    # ### end Alembic commands ###
