import * as Dialog from "@radix-ui/react-dialog";
import * as Switch from "@radix-ui/react-switch";
import { Activity, AlertCircle, ArrowLeft, CheckCircle2, ChevronRight, Globe2, KeyRound, LayoutDashboard, LoaderCircle, LogOut, Plus, RefreshCw, Search, Settings as SettingsIcon, ShieldCheck, Trash2, Users, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api, ApiError } from "./api";
import type { AdminDomain, AdminUser, Check, Domain, Page, Settings, Task, User } from "./types";

type Route = "dashboard" | "domains" | "tasks" | "settings" | "admin-users" | "admin-domains";
const routeFromHash = (): Route => (location.hash.slice(1) as Route) || "dashboard";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const errorText = (error: unknown) => error instanceof Error ? error.message : "操作未完成，请稍后重试";

function useRoute() { const [route, setRoute] = useState<Route>(routeFromHash); useEffect(() => { const update = () => setRoute(routeFromHash()); addEventListener("hashchange", update); return () => removeEventListener("hashchange", update); }, []); return [route, (value: Route) => { location.hash = value; }] as const; }
function Flash({ message }: { message: string | null }) { return message ? <div className="flash"><AlertCircle size={17} />{message}</div> : null; }
function Status({ status }: { status: Task["status"] | Check["outcome"] }) { const failed = status === "failed"; const pending = status === "queued" || status === "running"; return <span className={`status ${failed ? "status-failed" : pending ? "status-pending" : "status-healthy"}`}><i />{status === "succeeded" ? "已完成" : status === "queued" ? "排队中" : status === "running" ? "执行中" : failed ? "失败" : status}</span>; }

export function App() {
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [route, go] = useRoute(); const [flash, setFlash] = useState<string | null>(null);
  useEffect(() => { if (!api.restoreTokens()) { setReady(true); return; } api.me().then(setUser).catch(() => api.setTokens(null)).finally(() => setReady(true)); }, []);
  useEffect(() => { if (flash) { const id = setTimeout(() => setFlash(null), 4200); return () => clearTimeout(id); } }, [flash]);
  const authenticate = (result: { user: User; tokens: { access_token: string; refresh_token: string; expires_in: number } }) => { api.setTokens(result.tokens); setUser(result.user); location.hash = "dashboard"; };
  if (!ready) return <div className="loading-screen"><LoaderCircle className="spin" /> 正在连接服务…</div>;
  if (!user) return <AuthScreen onSuccess={authenticate} />;
  return <div className="shell"><Sidebar user={user} route={route} go={go} onLogout={() => api.logout().finally(() => { setUser(null); location.hash = "dashboard"; })} /><main className="content"><Flash message={flash} />{route === "dashboard" && <Dashboard go={go} />}{route === "domains" && <Domains onMessage={setFlash} />}{route === "tasks" && <Tasks />}{route === "settings" && <SettingsPage user={user} onUser={setUser} onMessage={setFlash} />}{route === "admin-users" && user.role === "admin" && <AdminUsers onMessage={setFlash} />}{route === "admin-domains" && user.role === "admin" && <AdminDomains />}</main></div>;
}

function AuthScreen({ onSuccess }: { onSuccess: (result: { user: User; tokens: { access_token: string; refresh_token: string; expires_in: number } }) => void }) {
  const [register, setRegister] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(null); try { const username = String(data.get("username")); const password = String(data.get("password")); onSuccess(register ? await api.register(username, password, String(data.get("email") || "")) : await api.login(username, password)); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <div className="auth"><section className="auth-card"><div className="brand"><span className="brand-mark"><Globe2 size={18} /></span>Domains<span>Manager</span></div><h1>{register ? "创建账号" : "欢迎回来"}</h1><p>{register ? "开始集中管理你的域名资产。" : "登录后继续管理域名资产。"}</p><form onSubmit={submit}>{register && <label>邮箱（可选）<input name="email" type="email" placeholder="name@example.com" /></label>}<label>用户名<input name="username" required minLength={3} placeholder="请输入用户名" /></label><label>密码<input name="password" type="password" required minLength={6} placeholder="至少 6 位字符" /></label>{error && <div className="form-error">{error}</div>}<button className="primary wide" disabled={busy}>{busy && <LoaderCircle className="spin" size={17} />}{register ? "创建并登录" : "登录"}</button></form><button className="auth-switch" onClick={() => setRegister(!register)}>{register ? "已有账号？登录" : "没有账号？注册"}</button></section></div>;
}

function Sidebar({ user, route, go, onLogout }: { user: User; route: Route; go: (r: Route) => void; onLogout: () => void }) { const Item = ({ value, icon: Icon, children }: { value: Route; icon: typeof Globe2; children: string }) => <button onClick={() => go(value)} className={`nav-item ${route === value ? "nav-active" : ""}`}><Icon size={18} />{children}</button>; return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Globe2 size={18} /></span>Domains<span>Manager</span></div><nav><p className="nav-label">工作台</p><Item value="dashboard" icon={LayoutDashboard}>仪表盘</Item><Item value="domains" icon={Globe2}>我的域名</Item><Item value="tasks" icon={Activity}>刷新任务</Item>{user.role === "admin" && <><p className="nav-label nav-spaced">管理</p><Item value="admin-users" icon={Users}>用户管理</Item><Item value="admin-domains" icon={ShieldCheck}>全局域名</Item></>}</nav><div className="sidebar-footer"><Item value="settings" icon={SettingsIcon}>设置</Item><button className="nav-item" onClick={onLogout}><LogOut size={18} />退出登录</button><div className="signed-user"><b>{user.username.slice(0, 1).toUpperCase()}</b><span>{user.username}<small>{user.role === "admin" ? "管理员" : "普通用户"}</small></span></div></div></aside>; }

function Dashboard({ go }: { go: (route: Route) => void }) { const [data, setData] = useState<Page<Domain> | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { api.domains({ page_size: 100, sort: "-created_at" }).then(setData).catch((e) => setError(errorText(e))); }, []); if (error) return <ErrorState message={error} />; if (!data) return <Loading />; const monitored = data.items.filter((d) => d.monitor_enabled).length; const manual = data.items.filter((d) => d.renewal_mode === "manual").length; return <><header className="page-head"><div><h1>域名资产概览</h1><p>基于当前已管理的域名记录。</p></div><button className="primary" onClick={() => go("domains")}><Plus size={17} />添加域名</button></header><section className="metrics"><Metric label="管理中的域名" value={String(data.total)} detail="当前账号的全部资产" /><Metric label="开启监控" value={String(monitored)} detail="会参与后续检查" /><Metric label="手动续期" value={String(manual)} detail="建议关注续期安排" /><Metric label="最近新增" value={data.items[0] ? date(data.items[0].created_at).split(" ")[0] : "—"} detail="按创建时间排序" /></section><section className="panel"><div className="panel-head"><div><h2>最近管理的域名</h2><p>数据来自 <code>GET /domains</code></p></div><button className="text-button" onClick={() => go("domains")}>全部域名 <ChevronRight size={16} /></button></div><DomainTable items={data.items.slice(0, 6)} /></section></>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <section className="metric-card"><p>{label}</p><strong>{value}</strong><span>{detail}</span></section>; }

function Domains({ onMessage }: { onMessage: (value: string) => void }) { const [data, setData] = useState<Page<Domain> | null>(null); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Domain | null>(null); const [addOpen, setAddOpen] = useState(false); const load = useCallback(() => api.domains({ query: query || undefined, page_size: 50, sort: "name" }).then(setData).catch((e) => onMessage(errorText(e))), [query, onMessage]); useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]); return <><header className="page-head"><div><h1>我的域名</h1><p>域名信息仅由刷新任务写入，手工编辑仅影响本地管理属性。</p></div><button className="primary" onClick={() => setAddOpen(true)}><Plus size={17} />添加域名</button></header><section className="panel"><div className="toolbar"><label className="search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索域名" /></label><span className="table-count">{data?.total ?? "—"} 个域名</span></div>{data ? <DomainTable items={data.items} onSelect={setSelected} /> : <Loading />}</section><AddDomain open={addOpen} onOpenChange={setAddOpen} onCreated={(domain) => { setAddOpen(false); setSelected(domain); load(); }} onMessage={onMessage} />{selected && <DomainDetail initial={selected} onClose={() => { setSelected(null); load(); }} onMessage={onMessage} />}</>; }
function DomainTable({ items, onSelect }: { items: Domain[]; onSelect?: (domain: Domain) => void }) { return <div className="table-wrap"><table><thead><tr><th>域名</th><th>续期方式</th><th>监控</th><th>最后更新</th><th /></tr></thead><tbody>{items.map((domain) => <tr key={domain.id} onClick={() => onSelect?.(domain)}><td><strong className="domain-name">{domain.identity.unicode_name}</strong><small>{domain.identity.ascii_name} · .{domain.identity.tld}</small></td><td><span className="plain-badge">{domain.renewal_mode === "automatic" ? "自动续期" : domain.renewal_mode === "manual" ? "手动续期" : "未设置"}</span></td><td>{domain.monitor_enabled ? <span className="verified"><CheckCircle2 size={16} />已开启</span> : <span className="muted">未开启</span>}</td><td className="muted">{date(domain.updated_at)}</td><td><ChevronRight size={17} className="muted" /></td></tr>)}</tbody></table>{!items.length && <EmptyState text="尚未添加域名" />}</div>; }

function AddDomain({ open, onOpenChange, onCreated, onMessage }: { open: boolean; onOpenChange: (open: boolean) => void; onCreated: (domain: Domain) => void; onMessage: (message: string) => void }) { const [name, setName] = useState(""); const [monitor, setMonitor] = useState(true); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { onCreated(await api.createDomain(name, monitor)); setName(""); } catch (err) { onMessage(errorText(err)); } finally { setBusy(false); } } return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="overlay" /><Dialog.Content className="dialog"><Dialog.Close className="dialog-close"><X size={18} /></Dialog.Close><Dialog.Title>添加域名</Dialog.Title><Dialog.Description>仅支持可注册域名；系统会标准化 Unicode 与 Punycode 输入。</Dialog.Description><form onSubmit={submit}><label className="field-label">域名<input autoFocus required value={name} onChange={(e) => setName(e.target.value)} placeholder="例如 example.com" /></label><label className="toggle-line"><span><b>启用监控</b><small>添加后可随时调整</small></span><Switch.Root className="switch" checked={monitor} onCheckedChange={setMonitor}><Switch.Thumb className="switch-thumb" /></Switch.Root></label><div className="dialog-actions"><Dialog.Close asChild><button type="button" className="secondary">取消</button></Dialog.Close><button className="primary" disabled={busy}>添加域名</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>; }

function DomainDetail({ initial, onClose, onMessage }: { initial: Domain; onClose: () => void; onMessage: (message: string) => void }) { const [domain, setDomain] = useState(initial); const [checks, setChecks] = useState<Check[]>([]); const [task, setTask] = useState<Task | null>(null); const [saving, setSaving] = useState(false); const load = useCallback(async () => { try { const [current, history] = await Promise.all([api.domain(initial.id), api.checks(initial.id, { page_size: 20 })]); setDomain(current.data); setChecks(history.items); } catch (e) { onMessage(errorText(e)); } }, [initial.id, onMessage]); useEffect(() => { load(); }, [load]); useEffect(() => { if (!task || !["queued", "running"].includes(task.status)) return; const id = setInterval(() => api.task(task.id).then((next) => { setTask(next); if (next.status === "succeeded") load(); }).catch((e) => onMessage(errorText(e))), 2000); return () => clearInterval(id); }, [task, load, onMessage]); async function save(values: Partial<Pick<Domain, "monitor_enabled" | "renewal_mode" | "notes">>) { setSaving(true); try { const next = await api.updateDomain(domain.id, domain.version, values); setDomain(next.data); } catch (e) { onMessage(e instanceof ApiError && e.status === 409 ? "记录已被更新，请关闭后重新打开。" : errorText(e)); } finally { setSaving(false); } } async function refresh() { try { const next = await api.refreshDomain(domain.id); setTask(next); const tasks = JSON.parse(sessionStorage.getItem("domainsmanager.tasks") || "[]") as string[]; sessionStorage.setItem("domainsmanager.tasks", JSON.stringify([...new Set([next.id, ...tasks])].slice(0, 30))); } catch (e) { onMessage(errorText(e)); } }
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer wide-drawer" onClick={(e) => e.stopPropagation()}><button className="drawer-close" onClick={onClose}><X size={19} /></button><span className="eyebrow">域名详情</span><h2>{domain.identity.unicode_name}</h2><p className="muted">{domain.identity.ascii_name} · 公共后缀 {domain.identity.public_suffix}</p><section className="detail-grid"><label className="toggle-line"><span><b>域名监控</b><small>控制后续监控任务</small></span><Switch.Root className="switch" checked={domain.monitor_enabled} onCheckedChange={(monitor_enabled) => save({ monitor_enabled })}><Switch.Thumb className="switch-thumb" /></Switch.Root></label><label className="field-label">续期方式<select value={domain.renewal_mode || "unknown"} onChange={(e) => save({ renewal_mode: e.target.value as Domain["renewal_mode"] })}><option value="unknown">未知</option><option value="automatic">自动续期</option><option value="manual">手动续期</option></select></label><label className="field-label full">备注<textarea value={domain.notes || ""} onChange={(e) => setDomain({ ...domain, notes: e.target.value })} onBlur={(e) => save({ notes: e.target.value })} placeholder="记录续费、所有权或操作说明" /></label></section><button className="primary wide" onClick={refresh} disabled={saving || !!task && ["queued", "running"].includes(task.status)}><RefreshCw size={17} className={task && ["queued", "running"].includes(task.status) ? "spin" : ""} />{task && ["queued", "running"].includes(task.status) ? "刷新任务执行中" : "立即刷新"}</button>{task && <div className="task-inline"><span>刷新任务</span><Status status={task.status} />{task.error && <small>{task.error.message}</small>}</div>}<section className="history"><div className="section-title"><b>检查历史</b><small>来自 GET /domains/{`{id}`}/checks</small></div>{checks.map((check) => <article className="history-row" key={check.id}><span><Status status={check.outcome} /><b>{date(check.checked_at)}</b><small>{check.protocol?.toUpperCase() || "—"} · {check.duration_ms ? `${check.duration_ms} ms` : ""}</small></span>{check.error_message && <em>{check.error_message}</em>}{check.changed_fields.length > 0 && <em>已变更：{check.changed_fields.join("、")}</em>}</article>)}{!checks.length && <EmptyState text="暂无检查记录；可点击“立即刷新”创建任务。" />}</section><button className="danger-link" onClick={async () => { if (confirm(`确认移除 ${domain.identity.ascii_name}？历史记录会保留。`)) { try { await api.deleteDomain(domain.id); onClose(); } catch (e) { onMessage(errorText(e)); } } }}><Trash2 size={15} />移除域名</button></aside></div>; }

function Tasks() { const [tasks, setTasks] = useState<Task[]>([]); const ids = useMemo(() => JSON.parse(sessionStorage.getItem("domainsmanager.tasks") || "[]") as string[], []); useEffect(() => { const load = () => Promise.all(ids.map((id) => api.task(id).catch(() => null))).then((values) => setTasks(values.filter(Boolean) as Task[])); load(); const id = setInterval(load, 2500); return () => clearInterval(id); }, [ids]); return <><header className="page-head"><div><h1>刷新任务</h1><p>此处显示本浏览器会话中创建的异步刷新任务。</p></div></header><section className="panel"><div className="table-wrap"><table><thead><tr><th>状态</th><th>任务 ID</th><th>创建时间</th><th>完成时间</th><th>结果</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><Status status={task.status} /></td><td className="mono">{task.id}</td><td>{date(task.created_at)}</td><td>{date(task.completed_at)}</td><td>{task.error?.message || (task.check_id ? "已生成检查记录" : "—")}</td></tr>)}</tbody></table>{!tasks.length && <EmptyState text="尚无刷新任务。域名详情页的“立即刷新”会在此显示。" />}</div></section></>; }

function SettingsPage({ user, onUser, onMessage }: { user: User; onUser: (user: User) => void; onMessage: (message: string) => void }) { const [settings, setSettings] = useState<Settings | null>(null); const [email, setEmail] = useState(user.email || ""); const [passwords, setPasswords] = useState({ current: "", next: "" }); useEffect(() => { api.settings().then(setSettings).catch((e) => onMessage(errorText(e))); }, [onMessage]); return <><header className="page-head"><div><h1>设置</h1><p>管理个人资料、安全与默认监控偏好。</p></div></header><div className="settings-grid"><section className="panel form-panel"><h2>个人资料</h2><label className="field-label">用户名<input value={user.username} disabled /></label><label className="field-label">邮箱<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><button className="primary" onClick={async () => { try { onUser(await api.updateMe(email)); onMessage("个人资料已保存"); } catch (e) { onMessage(errorText(e)); } }}>保存资料</button></section><section className="panel form-panel"><h2>安全</h2><label className="field-label">当前密码<input type="password" value={passwords.current} onChange={(e) => setPasswords({ ...passwords, current: e.target.value })} /></label><label className="field-label">新密码<input type="password" minLength={6} value={passwords.next} onChange={(e) => setPasswords({ ...passwords, next: e.target.value })} /></label><button className="secondary" onClick={async () => { try { await api.changePassword(passwords.current, passwords.next); setPasswords({ current: "", next: "" }); onMessage("密码已更新，其他会话已被撤销"); } catch (e) { onMessage(errorText(e)); } }}><KeyRound size={16} />更新密码</button></section>{settings && <section className="panel form-panel"><h2>默认偏好</h2><label className="toggle-line"><span><b>默认开启监控</b><small>添加域名时的默认值</small></span><Switch.Root className="switch" checked={settings.default_monitor_enabled} onCheckedChange={async (default_monitor_enabled) => { try { setSettings(await api.updateSettings({ default_monitor_enabled })); } catch (e) { onMessage(errorText(e)); } }}><Switch.Thumb className="switch-thumb" /></Switch.Root></label><label className="field-label">时区<input value={settings.timezone} onChange={(e) => setSettings({ ...settings, timezone: e.target.value })} onBlur={async () => { try { setSettings(await api.updateSettings({ timezone: settings.timezone })); } catch (e) { onMessage(errorText(e)); } }} /></label></section>}</div></>; }

function AdminUsers({ onMessage }: { onMessage: (message: string) => void }) { const [data, setData] = useState<Page<AdminUser> | null>(null); const [query, setQuery] = useState(""); const load = useCallback(() => api.adminUsers({ query: query || undefined, page_size: 100 }).then(setData).catch((e) => onMessage(errorText(e))), [query, onMessage]); useEffect(() => { load(); }, [load]); return <><header className="page-head"><div><h1>用户管理</h1><p>封禁会立即撤销目标用户的所有会话。</p></div></header><section className="panel"><div className="toolbar"><label className="search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="按用户名搜索" /></label></div>{data && <div className="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>域名数</th><th>状态</th><th /></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td><strong>{item.username}</strong><small>{item.email || "未设置邮箱"}</small></td><td>{item.role === "admin" ? "管理员" : "用户"}</td><td>{item.domain_count}</td><td><Status status={item.status === "banned" ? "failed" : "succeeded"} /></td><td><button className="refresh" onClick={async () => { try { if (item.status === "banned") await api.unbanUser(item.id); else { const reason = prompt("请输入封禁原因（至少 3 个字符）："); if (!reason) return; await api.banUser(item.id, reason); } load(); } catch (e) { onMessage(errorText(e)); } }}>{item.status === "banned" ? "解除封禁" : "封禁"}</button></td></tr>)}</tbody></table></div>}</section></>; }
function AdminDomains() { const [data, setData] = useState<Page<AdminDomain> | null>(null); const [query, setQuery] = useState(""); useEffect(() => { const id = setTimeout(() => api.adminDomains({ query: query || undefined, page_size: 100 }).then(setData), 150); return () => clearTimeout(id); }, [query]); return <><header className="page-head"><div><h1>全局域名</h1><p>管理员视图包含域名所有者与软删除状态。</p></div></header><section className="panel"><div className="toolbar"><label className="search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索全局域名" /></label></div>{data && <div className="table-wrap"><table><thead><tr><th>域名</th><th>所有者</th><th>监控</th><th>状态</th><th>创建时间</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td><strong>{item.identity.ascii_name}</strong><small>{item.identity.public_suffix}</small></td><td>{item.owner.username}</td><td>{item.monitor_enabled ? "已开启" : "未开启"}</td><td>{item.deleted_at ? <span className="status status-failed"><i />已删除</span> : <span className="status status-healthy"><i />正常</span>}</td><td>{date(item.created_at)}</td></tr>)}</tbody></table></div>}</section></>; }
function Loading() { return <div className="loading"><LoaderCircle className="spin" size={20} />加载中…</div>; } function EmptyState({ text }: { text: string }) { return <div className="empty"><Globe2 size={21} />{text}</div>; } function ErrorState({ message }: { message: string }) { return <div className="empty"><AlertCircle size={21} />{message}</div>; }
